UPDATE public.page_content
SET content = jsonb_set(
  content,
  '{paragraphs}',
  to_jsonb(ARRAY[
    'O grupo <strong>Migrações, Mobilidades e Gestão Contemporânea de Populações (MIGRA)</strong> foi criado em <strong>2019</strong>, no Departamento de Ciências Geográficas da <strong>Universidade Federal de Pernambuco (UFPE)</strong>, a partir da atuação dos professores <strong>Bertrand Cozic</strong> e <strong>Carol Leite</strong>, contando posteriormente com a entrada da professora <strong>Sofia Zanforlin</strong>, do Departamento de Comunicação. Com perfil <strong>interdisciplinar</strong>, o grupo estruturou-se em torno de duas linhas de pesquisa: (1) <strong>As migrações contemporâneas: territórios, culturas e economia no mundo globalizado</strong>; e (2) <strong>Comunicação e interculturalidade, pertencimento, consumo cultural e cidadania</strong>.',
    'As primeiras ações do grupo incluíram os projetos de extensão <strong>Rádio Migra — a construção de uma rádio migrante</strong> — e <strong>Cartografias</strong>, ambos impactados pela <strong>pandemia de 2020</strong>, que inviabilizou atividades presenciais como entrevistas e mapeamentos na cidade do Recife. Nesse período, passaram a ser realizados <strong>encontros virtuais semanais</strong>, abertos ao público, voltados à leitura e ao debate de textos fundamentais do campo.',
    'Em <strong>2021</strong>, o MIGRA desenvolveu diferentes projetos, entre eles um <strong>curso de extensão</strong> destinado à formação de trabalhadores, servidoras e servidores públicos vinculados ao atendimento de migrantes em Pernambuco, em parceria com instituições como a <strong>Cáritas</strong>. No mesmo ano, o grupo realizou o minidocumentário <strong>Así Passó</strong>. Ainda em 2021, foi aprovado o projeto de pesquisa <strong>Fronteiras da mobilidade no Brasil contemporâneo: comunicação e experiência migrante na securitização do acolhimento e da integração social no âmbito da Operação Acolhida</strong>, financiado pelo <strong>CNPq</strong> (Chamada CNPq/MCTI/FNDCT nº 18/2021), em parceria entre a <strong>UFPE</strong> e a <strong>Universidade Federal de Roraima (UFRR)</strong>.',
    'A pesquisa realizou trabalhos de campo em <strong>Roraima, em 2022</strong>, e em <strong>Brasília, em 2023</strong>, envolvendo visitas a abrigos da <strong>Operação Acolhida</strong>, ocupações de migrantes venezuelanos e entrevistas com gestores públicos e representantes de organismos internacionais, como <strong>OIM</strong> e <strong>ACNUR</strong>, com o objetivo de compreender as diretrizes e a estruturação desse modelo de acolhimento no Brasil.',
    'Em <strong>2024</strong>, foi aprovado um novo projeto no <strong>edital Universal (Chamada CNPq/MCTI nº 44/2024)</strong>, coordenado pela professora <strong>Sofia Zanforlin</strong> e desenvolvido com a participação da equipe anterior, com destaque para as pesquisadoras <strong>Júlia Lyra</strong> e <strong>Raíra Tavares</strong>. Intitulado <strong>Digitalização da fronteira, migração digital e bios midiático: securitização, humanitarismo e plataformização do trabalho na Operação Acolhida (OPA)</strong>, o estudo aprofunda os achados anteriores e investiga os processos de <strong>digitalização das fronteiras</strong>, <strong>datificação da mobilidade</strong>, <strong>vigilância</strong> e <strong>plataformização do trabalho</strong>, em diálogo com epistemologias críticas a partir do conceito de <strong>bios midiático (Sodré, 2014)</strong>.',
    'Atualmente, o grupo é coordenado pelas professoras <strong>Sofia Zanforlin</strong>, no campo da Comunicação, e <strong>Carol Leite</strong>, no campo da Geografia.'
  ]::text[])
)
WHERE page = 'sobre' AND section_key = 'historia';

UPDATE public.page_content
SET content = jsonb_build_object(
  'title', COALESCE(content->>'title', 'Sobre o projeto'),
  'paragraphs', jsonb_build_array(
    'O projeto <strong>Rádio Migra — a construção de uma rádio migrante</strong> consiste na produção de <strong>podcasts sobre migrações internacionais</strong> e está vinculado ao <strong>grupo de pesquisa MIGRA</strong>. A iniciativa foi concebida em parceria com o projeto de extensão <strong>Cartografias Migrantes</strong>, no qual os trabalhos de campo forneceram o contexto para entrevistas e produção de materiais, em diálogo com grupos de migrantes e instituições que atuam na questão migratória em Pernambuco.',
    'Com a <strong>pandemia</strong>, o projeto precisou ser adaptado: as saídas de campo foram suspensas, assim como o acesso aos estúdios e ao suporte técnico, exigindo da equipe alternativas viáveis de <strong>produção remota</strong>. O primeiro semestre foi dedicado à seleção de estudantes bolsistas e voluntários; no segundo, com o grupo formado, iniciaram-se reuniões semanais para definição de pautas e produção do primeiro episódio. Em julho, sob supervisão do <strong>professor Bruno Nogueira</strong>, os estudantes participaram de uma oficina sobre edição e produção caseira de podcasts.',
    'O primeiro episódio aborda as dimensões históricas e contemporâneas da <strong>migração chinesa para Pernambuco</strong>. O segundo episódio trata da <strong>Operação Acolhida</strong>. Em seguida, a rádio retorna pelo <strong>edital BICC</strong> com os estudantes Ícaro Ricarte e Isabel Bahé na coordenação.'
  )
)
WHERE page = 'radio' AND section_key = 'about';